title: "Наша библиотека решений"
description: "Сайт с решениями задач из книг"
baseurl: "/TrynaGetSmarter"
url: "https://bzzzrka.github.io"
#theme: minima

permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
